import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { activities, itineraryDays, trips, users } from "@/db/schema";
import { generateStructuredJson } from "@/lib/gemini";
import { getLocationImageUrl } from "@/lib/location-image";
import {
  normalizeEstimatedCostForDb,
  normalizeEstimatedCurrency,
  normalizeEstimateNote
} from "@/lib/trip-pricing";

export const runtime = "nodejs";

type GenerateTripRequest = {
  userId?: string;
  userEmail?: string;
  travelerCountry?: string;
  destination?: string;
  startDate?: string;
  endDate?: string;
  budgetTier?: string;
  travelGroup?: string;
  vibe?: string[];
  dietaryPrefs?: string[];
  mustDos?: string;
};

type GeneratedActivity = {
  time: string;
  type: "food" | "landmark" | "transit";
  title: string;
  description: string;
  cost_estimate: string | null;
};

type GeneratedDay = {
  day_number: number;
  date: string;
  activities: GeneratedActivity[];
};

type GeneratedItinerary = {
  estimated_total: string | number | null;
  currency_code: string | null;
  pricing_note: string | null;
  days: GeneratedDay[];
};

const validActivityTypes = new Set(["food", "landmark", "transit"]);

function parseStatusFromMessage(message: string) {
  const match = message.match(/\[(\d{3})\s*[A-Za-z ]*\]/) || message.match(/\b(\d{3})\b/);
  return match ? Number(match[1]) : null;
}

function isTransientAiLoadError(message: string) {
  const lower = message.toLowerCase();
  const status = parseStatusFromMessage(lower);

  if (status && [429, 500, 502, 503, 504].includes(status)) {
    return true;
  }

  return (
    lower.includes("service unavailable") ||
    lower.includes("high demand") ||
    lower.includes("try again later") ||
    lower.includes("temporarily unavailable")
  );
}

function isValidDateString(value: string) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  return !Number.isNaN(new Date(`${value}T00:00:00Z`).getTime());
}

function daysBetweenInclusive(startDate: string, endDate: string) {
  const start = new Date(`${startDate}T00:00:00Z`);
  const end = new Date(`${endDate}T00:00:00Z`);
  return Math.floor((end.getTime() - start.getTime()) / 86400000) + 1;
}

function addDays(dateString: string, amount: number) {
  const date = new Date(`${dateString}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + amount);
  return date.toISOString().split("T")[0];
}

function safeArray(value: unknown) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => String(item).trim())
    .filter(Boolean);
}

function parsePositiveInt(value: unknown) {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) return null;
  return parsed;
}

function buildSeededFallbackImage(destination: string, title: string, type: string) {
  return `https://picsum.photos/seed/${encodeURIComponent(
    `${destination}|${title}|${type}`
  )}/960/640`;
}

function sanitizeItinerary(
  rawOutput: unknown,
  startDate: string,
  totalDays: number
): GeneratedDay[] {
  const fallbackDays = Array.from({ length: totalDays }, (_, index) => ({
    day_number: index + 1,
    date: addDays(startDate, index),
    activities: [
      {
        time: "09:00",
        type: "landmark" as const,
        title: "Free Exploration Block",
        description: "Use this block for a local recommendation or spontaneous plan.",
        cost_estimate: null
      }
    ]
  }));

  if (!rawOutput || typeof rawOutput !== "object") return fallbackDays;
  const rawDays = (rawOutput as GeneratedItinerary).days;
  if (!Array.isArray(rawDays)) return fallbackDays;

  return Array.from({ length: totalDays }, (_, index) => {
    const dayNumber = index + 1;
    const matchingDay =
      rawDays.find((day) => Number(day?.day_number) === dayNumber) || rawDays[index];

    const safeDate =
      matchingDay?.date && isValidDateString(String(matchingDay.date))
        ? String(matchingDay.date)
        : addDays(startDate, index);

    const rawActivities = Array.isArray(matchingDay?.activities)
      ? matchingDay.activities
      : [];

    const activitiesForDay: GeneratedActivity[] = rawActivities
      .slice(0, 6)
      .map((activity) => {
        const parsedType = String(activity?.type || "").toLowerCase();
        const type = validActivityTypes.has(parsedType)
          ? (parsedType as GeneratedActivity["type"])
          : "landmark";
        const time = /^\d{2}:\d{2}$/.test(String(activity?.time || ""))
          ? String(activity.time)
          : "09:00";
        const title = String(activity?.title || "").trim() || "Activity Suggestion";
        const description =
          String(activity?.description || "").trim() ||
          "A local activity generated by TripSense.";
        const cost_estimate = activity?.cost_estimate
          ? String(activity.cost_estimate)
          : null;

        return {
          time,
          type,
          title,
          description,
          cost_estimate
        };
      })
      .filter((activity) => activity.title && activity.description);

    return {
      day_number: dayNumber,
      date: safeDate,
      activities:
        activitiesForDay.length > 0 ? activitiesForDay : fallbackDays[index].activities
    };
  });
}

function buildGeneratePrompt(input: {
  destination: string;
  startDate: string;
  endDate: string;
  totalDays: number;
  budgetTier: string;
  travelGroup: string;
  vibe: string[];
  dietaryPrefs: string[];
  mustDos: string;
  travelerCountry: string;
}) {
  return `
SYSTEM INSTRUCTIONS:
You are TripSense's itinerary engine. Return ONLY valid JSON, without markdown or code fences.

REQUIRED JSON SHAPE:
{
  "estimated_total": 0,
  "currency_code": "USD",
  "pricing_note": "short explanation",
  "days": [
    {
      "day_number": 1,
      "date": "YYYY-MM-DD",
      "activities": [
        {
          "time": "HH:MM",
          "type": "food | landmark | transit",
          "title": "short title",
          "description": "1-2 sentence description",
          "cost_estimate": "string or null"
        }
      ]
    }
  ]
}

RULES:
- Return one realistic trip total estimate for the full trip in estimated_total.
- estimated_total should be a plain number, not a formatted string.
- Include accommodation, local transport, food, and major activity tickets in the estimate.
- Exclude international flights, visa fees, and personal shopping.
- Use the traveler's currency when travelerCountry is provided. If no travelerCountry is provided, use USD.
- currency_code must be a 3-letter ISO style currency code such as USD, INR, EUR, JPY.
- pricing_note should be one short sentence explaining what is included.
- Generate exactly ${input.totalDays} day objects.
- day_number must start from 1 and be sequential.
- Dates must stay in range ${input.startDate} to ${input.endDate}.
- Each day should have 3 to 5 activities.
- type must be one of: food, landmark, transit.
- time must be in 24-hour HH:MM format.
- Keep plan realistic with short transit and budget-aware options.
- Respect dietary preferences and must-dos/dealbreakers strictly.

TRIP INPUT:
${JSON.stringify(
    {
      destination: input.destination,
      startDate: input.startDate,
      endDate: input.endDate,
      budgetTier: input.budgetTier,
      travelGroup: input.travelGroup,
      vibe: input.vibe,
      dietaryPrefs: input.dietaryPrefs,
      mustDos: input.mustDos || "None",
      travelerCountry: input.travelerCountry || "Guest / Unknown"
    },
    null,
    2
  )}
`;
}

async function resolveUserId(
  tx: any,
  payload: GenerateTripRequest
) {
  if (payload.userId?.trim()) {
    const parsedUserId = parsePositiveInt(payload.userId.trim());
    if (!parsedUserId) {
      throw new Error("userId must be a positive integer");
    }
    return parsedUserId;
  }
  if (!payload.userEmail?.trim()) {
    throw new Error("userId or userEmail is required");
  }

  const email = payload.userEmail.toLowerCase().trim();
  const existingUser = await tx
    .select({ id: users.id })
    .from(users)
    .where(eq(users.email, email))
    .limit(1);

  if (existingUser.length > 0) {
    return existingUser[0].id;
  }

  const [createdUser] = await tx
    .insert(users)
    .values({ email })
    .returning({ id: users.id });

  return createdUser.id;
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as GenerateTripRequest;

    const destination = String(body.destination || "").trim();
    const startDate = String(body.startDate || "").trim();
    const endDate = String(body.endDate || "").trim();
    const budgetTier = String(body.budgetTier || "").trim();
    const travelGroup = String(body.travelGroup || "").trim();
    const vibe = safeArray(body.vibe);
    const dietaryPrefs = safeArray(body.dietaryPrefs);
    const mustDos = String(body.mustDos || "").trim();
    const travelerCountry = String(body.travelerCountry || "").trim();

    if (!destination || !startDate || !endDate || !budgetTier || !travelGroup) {
      return NextResponse.json(
        { error: "Missing required questionnaire fields." },
        { status: 400 }
      );
    }

    if (!isValidDateString(startDate) || !isValidDateString(endDate)) {
      return NextResponse.json(
        { error: "Dates must be in YYYY-MM-DD format." },
        { status: 400 }
      );
    }

    const totalDays = daysBetweenInclusive(startDate, endDate);
    if (totalDays <= 0 || totalDays > 30) {
      return NextResponse.json(
        { error: "Invalid date range. Trip length must be between 1 and 30 days." },
        { status: 400 }
      );
    }

    const prompt = buildGeneratePrompt({
      destination,
      startDate,
      endDate,
      totalDays,
      budgetTier,
      travelGroup,
      vibe,
      dietaryPrefs,
      mustDos,
      travelerCountry
    });

    const geminiOutput = await generateStructuredJson<GeneratedItinerary>({
      prompt,
      temperature: 0.3
    });

    const sanitizedDays = sanitizeItinerary(geminiOutput, startDate, totalDays);
    const estimatedCost = normalizeEstimatedCostForDb(geminiOutput?.estimated_total);
    const estimatedCurrency = normalizeEstimatedCurrency(geminiOutput?.currency_code);
    const estimatedCostNote = normalizeEstimateNote(geminiOutput?.pricing_note);
    let createdTripId: number | null = null;
    const imageCache = new Map<string, string>();
    const usedImageUrls = new Set<string>();

    try {
      const userId = await resolveUserId(db, body);

      const [newTrip] = await db
        .insert(trips)
        .values({
          userId,
          destination,
          startDate,
          endDate,
          budgetTier,
          travelGroup,
          vibe,
          dietaryPrefs,
          mustDos,
          estimatedCost,
          estimatedCurrency,
          estimatedCostNote
        })
        .returning({ id: trips.id });

      createdTripId = newTrip.id;

      for (const day of sanitizedDays) {
        const [createdDay] = await db
          .insert(itineraryDays)
          .values({
            tripId: newTrip.id,
            dayNumber: day.day_number,
            date: day.date
          })
          .returning({ id: itineraryDays.id });

        if (day.activities.length > 0) {
          const activityRows = await Promise.all(
            day.activities.map(async (activity) => {
              const cacheKey = `${destination}|${activity.title}|${activity.type}`;
              let imageUrl = imageCache.get(cacheKey);

              if (!imageUrl) {
                imageUrl = await getLocationImageUrl({
                  destination,
                  title: activity.title,
                  type: activity.type
                });
                imageCache.set(cacheKey, imageUrl);
              }

              if (usedImageUrls.has(imageUrl)) {
                const retryImage = await getLocationImageUrl({
                  destination,
                  title: `${activity.title} ${activity.type}`,
                  type: activity.type
                });

                if (!usedImageUrls.has(retryImage)) {
                  imageUrl = retryImage;
                }
              }

              if (usedImageUrls.has(imageUrl)) {
                imageUrl = buildSeededFallbackImage(
                  destination,
                  activity.title,
                  activity.type
                );
              }

              usedImageUrls.add(imageUrl);

              return {
                dayId: createdDay.id,
                time: activity.time,
                type: activity.type,
                title: activity.title,
                description: activity.description,
                costEstimate: normalizeEstimatedCostForDb(activity.cost_estimate),
                imageUrl
              };
            })
          );

          await db.insert(activities).values(
            activityRows
          );
        }
      }

      return NextResponse.json({ tripId: newTrip.id }, { status: 201 });
    } catch (saveError) {
      if (createdTripId) {
        // Manual rollback path for neon-http (no interactive transactions).
        await db.delete(trips).where(eq(trips.id, createdTripId));
      }
      throw saveError;
    }
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Failed to generate itinerary.";

    if (isTransientAiLoadError(message)) {
      return NextResponse.json(
        {
          error:
            "TripSense AI is busy right now. Please wait a few seconds and click Generate Trip again.",
          details: message
        },
        { status: 503 }
      );
    }

    const status =
      message.includes("invalid JSON") || message.includes("Gemini")
        ? 502
        : message.includes("required")
          ? 400
          : 500;

    return NextResponse.json(
      {
        error: "Trip generation failed.",
        details: message
      },
      { status }
    );
  }
}
