import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { activities, itineraryDays, trips } from "@/db/schema";
import { generateStructuredJson } from "@/lib/gemini";
import { getLocationImageUrl } from "@/lib/location-image";

export const runtime = "nodejs";

type RouteContext = {
  params: {
    id: string;
  };
};

type UpdateTripRequest = {
  destination?: string;
  startDate?: string;
  endDate?: string;
  budgetTier?: string;
  travelGroup?: string;
  vibe?: string[];
  dietaryPrefs?: string[];
  mustDos?: string;
};

type GeneratedActivity = {
  time: string;
  type: "food" | "landmark" | "transit";
  title: string;
  description: string;
  cost_estimate: string | null;
};

type GeneratedDay = {
  day_number: number;
  date: string;
  activities: GeneratedActivity[];
};

type GeneratedItinerary = {
  days: GeneratedDay[];
};

const validActivityTypes = new Set(["food", "landmark", "transit"]);

function parsePositiveInt(value: unknown) {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) return null;
  return parsed;
}

function parseStatusFromMessage(message: string) {
  const match = message.match(/\[(\d{3})\s*[A-Za-z ]*\]/) || message.match(/\b(\d{3})\b/);
  return match ? Number(match[1]) : null;
}

function isTransientAiLoadError(message: string) {
  const lower = message.toLowerCase();
  const status = parseStatusFromMessage(lower);

  if (status && [429, 500, 502, 503, 504].includes(status)) {
    return true;
  }

  return (
    lower.includes("service unavailable") ||
    lower.includes("high demand") ||
    lower.includes("try again later") ||
    lower.includes("temporarily unavailable")
  );
}

function isValidDateString(value: string) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  return !Number.isNaN(new Date(`${value}T00:00:00Z`).getTime());
}

function daysBetweenInclusive(startDate: string, endDate: string) {
  const start = new Date(`${startDate}T00:00:00Z`);
  const end = new Date(`${endDate}T00:00:00Z`);
  return Math.floor((end.getTime() - start.getTime()) / 86400000) + 1;
}

function addDays(dateString: string, amount: number) {
  const date = new Date(`${dateString}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + amount);
  return date.toISOString().split("T")[0];
}

function safeArray(value: unknown) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => String(item).trim())
    .filter(Boolean);
}

function normalizeCostEstimateForDb(value: string | null) {
  if (!value) return null;

  const raw = String(value).trim();
  if (!raw || raw.toLowerCase() === "null" || raw.toLowerCase() === "n/a") {
    return null;
  }

  const numericPart = raw.replace(/[^0-9.]/g, "");
  if (!numericPart) return null;

  const parsed = Number(numericPart);
  return Number.isFinite(parsed) ? String(parsed) : null;
}

function sanitizeItinerary(
  rawOutput: unknown,
  startDate: string,
  totalDays: number
): GeneratedDay[] {
  const fallbackDays = Array.from({ length: totalDays }, (_, index) => ({
    day_number: index + 1,
    date: addDays(startDate, index),
    activities: [
      {
        time: "09:00",
        type: "landmark" as const,
        title: "Free Exploration Block",
        description: "Use this block for a local recommendation or spontaneous plan.",
        cost_estimate: null
      }
    ]
  }));

  if (!rawOutput || typeof rawOutput !== "object") return fallbackDays;
  const rawDays = (rawOutput as GeneratedItinerary).days;
  if (!Array.isArray(rawDays)) return fallbackDays;

  return Array.from({ length: totalDays }, (_, index) => {
    const dayNumber = index + 1;
    const matchingDay =
      rawDays.find((day) => Number(day?.day_number) === dayNumber) || rawDays[index];

    const safeDate =
      matchingDay?.date && isValidDateString(String(matchingDay.date))
        ? String(matchingDay.date)
        : addDays(startDate, index);

    const rawActivities = Array.isArray(matchingDay?.activities)
      ? matchingDay.activities
      : [];

    const activitiesForDay: GeneratedActivity[] = rawActivities
      .slice(0, 6)
      .map((activity) => {
        const parsedType = String(activity?.type || "").toLowerCase();
        const type = validActivityTypes.has(parsedType)
          ? (parsedType as GeneratedActivity["type"])
          : "landmark";
        const time = /^\d{2}:\d{2}$/.test(String(activity?.time || ""))
          ? String(activity.time)
          : "09:00";
        const title = String(activity?.title || "").trim() || "Activity Suggestion";
        const description =
          String(activity?.description || "").trim() ||
          "A local activity generated by TripSense.";
        const cost_estimate = activity?.cost_estimate
          ? String(activity.cost_estimate)
          : null;

        return {
          time,
          type,
          title,
          description,
          cost_estimate
        };
      })
      .filter((activity) => activity.title && activity.description);

    return {
      day_number: dayNumber,
      date: safeDate,
      activities:
        activitiesForDay.length > 0 ? activitiesForDay : fallbackDays[index].activities
    };
  });
}

function buildGeneratePrompt(input: {
  destination: string;
  startDate: string;
  endDate: string;
  totalDays: number;
  budgetTier: string;
  travelGroup: string;
  vibe: string[];
  dietaryPrefs: string[];
  mustDos: string;
}) {
  return `
SYSTEM INSTRUCTIONS:
You are TripSense's itinerary engine. Return ONLY valid JSON, without markdown or code fences.

REQUIRED JSON SHAPE:
{
  "days": [
    {
      "day_number": 1,
      "date": "YYYY-MM-DD",
      "activities": [
        {
          "time": "HH:MM",
          "type": "food | landmark | transit",
          "title": "short title",
          "description": "1-2 sentence description",
          "cost_estimate": "string or null"
        }
      ]
    }
  ]
}

RULES:
- Generate exactly ${input.totalDays} day objects.
- day_number must start from 1 and be sequential.
- Dates must stay in range ${input.startDate} to ${input.endDate}.
- Each day should have 3 to 5 activities.
- type must be one of: food, landmark, transit.
- time must be in 24-hour HH:MM format.
- Keep plan realistic with short transit and budget-aware options.
- Respect dietary preferences and must-dos/dealbreakers strictly.

TRIP INPUT:
${JSON.stringify(
    {
      destination: input.destination,
      startDate: input.startDate,
      endDate: input.endDate,
      budgetTier: input.budgetTier,
      travelGroup: input.travelGroup,
      vibe: input.vibe,
      dietaryPrefs: input.dietaryPrefs,
      mustDos: input.mustDos || "None"
    },
    null,
    2
  )}
`;
}

export async function POST(request: NextRequest, context: RouteContext) {
  try {
    const tripId = parsePositiveInt(context.params.id);
    if (!tripId) {
      return NextResponse.json({ error: "Trip id is required." }, { status: 400 });
    }

    const body = (await request.json()) as UpdateTripRequest;

    const [existingTrip] = await db
      .select({
        id: trips.id,
        userId: trips.userId,
        destination: trips.destination,
        startDate: trips.startDate,
        endDate: trips.endDate,
        budgetTier: trips.budgetTier,
        travelGroup: trips.travelGroup,
        vibe: trips.vibe,
        dietaryPrefs: trips.dietaryPrefs,
        mustDos: trips.mustDos,
        createdAt: trips.createdAt
      })
      .from(trips)
      .where(eq(trips.id, tripId))
      .limit(1);

    if (!existingTrip) {
      return NextResponse.json({ error: "Trip not found." }, { status: 404 });
    }

    const destination = String(body.destination ?? existingTrip.destination ?? "").trim();
    const startDate = String(body.startDate ?? existingTrip.startDate ?? "").trim();
    const endDate = String(body.endDate ?? existingTrip.endDate ?? "").trim();
    const budgetTier = String(body.budgetTier ?? existingTrip.budgetTier ?? "").trim();
    const travelGroup = String(body.travelGroup ?? existingTrip.travelGroup ?? "").trim();
    const vibe =
      body.vibe !== undefined ? safeArray(body.vibe) : safeArray(existingTrip.vibe);
    const dietaryPrefs =
      body.dietaryPrefs !== undefined
        ? safeArray(body.dietaryPrefs)
        : safeArray(existingTrip.dietaryPrefs);
    const mustDos =
      body.mustDos !== undefined
        ? String(body.mustDos || "").trim()
        : String(existingTrip.mustDos || "");

    if (!destination || !startDate || !endDate || !budgetTier || !travelGroup) {
      return NextResponse.json(
        { error: "Missing required plan fields." },
        { status: 400 }
      );
    }

    if (!isValidDateString(startDate) || !isValidDateString(endDate)) {
      return NextResponse.json(
        { error: "Dates must be in YYYY-MM-DD format." },
        { status: 400 }
      );
    }

    const totalDays = daysBetweenInclusive(startDate, endDate);
    if (totalDays <= 0 || totalDays > 30) {
      return NextResponse.json(
        { error: "Invalid date range. Trip length must be between 1 and 30 days." },
        { status: 400 }
      );
    }

    const prompt = buildGeneratePrompt({
      destination,
      startDate,
      endDate,
      totalDays,
      budgetTier,
      travelGroup,
      vibe,
      dietaryPrefs,
      mustDos
    });

    const geminiOutput = await generateStructuredJson<GeneratedItinerary>({
      prompt,
      temperature: 0.3
    });

    const sanitizedDays = sanitizeItinerary(geminiOutput, startDate, totalDays);

    await db
      .update(trips)
      .set({
        destination,
        startDate,
        endDate,
        budgetTier,
        travelGroup,
        vibe,
        dietaryPrefs,
        mustDos
      })
      .where(eq(trips.id, tripId));

    await db.delete(itineraryDays).where(eq(itineraryDays.tripId, tripId));

    const imageCache = new Map<string, string>();
    const responseDays: Array<{
      id: number;
      dayNumber: number;
      date: string;
      activities: Array<{
        id: number;
        time: string;
        type: "food" | "landmark" | "transit";
        title: string;
        description: string;
        costEstimate: string | null;
        imageUrl: string | null;
      }>;
    }> = [];

    for (const day of sanitizedDays) {
      const [createdDay] = await db
        .insert(itineraryDays)
        .values({
          tripId,
          dayNumber: day.day_number,
          date: day.date
        })
        .returning({
          id: itineraryDays.id,
          dayNumber: itineraryDays.dayNumber,
          date: itineraryDays.date
        });

      const dayActivities = await Promise.all(
        day.activities.map(async (activity) => {
          const cacheKey = `${destination}|${activity.title}|${activity.type}`;
          let imageUrl = imageCache.get(cacheKey);

          if (!imageUrl) {
            imageUrl = await getLocationImageUrl({
              destination,
              title: activity.title,
              type: activity.type
            });
            imageCache.set(cacheKey, imageUrl);
          }

          return {
            dayId: createdDay.id,
            time: activity.time,
            type: activity.type,
            title: activity.title,
            description: activity.description,
            costEstimate: normalizeCostEstimateForDb(activity.cost_estimate),
            imageUrl
          };
        })
      );

      const insertedActivities =
        dayActivities.length > 0
          ? await db
              .insert(activities)
              .values(dayActivities)
              .returning({
                id: activities.id,
                time: activities.time,
                type: activities.type,
                title: activities.title,
                description: activities.description,
                costEstimate: activities.costEstimate,
                imageUrl: activities.imageUrl
              })
          : [];

      responseDays.push({
        id: createdDay.id,
        dayNumber: createdDay.dayNumber,
        date: createdDay.date,
        activities: insertedActivities
      });
    }

    return NextResponse.json(
      {
        trip: {
          ...existingTrip,
          destination,
          startDate,
          endDate,
          budgetTier,
          travelGroup,
          vibe,
          dietaryPrefs,
          mustDos
        },
        days: responseDays
      },
      { status: 200 }
    );
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Failed to regenerate itinerary.";

    if (isTransientAiLoadError(message)) {
      return NextResponse.json(
        {
          error:
            "TripSense AI is busy right now. Please wait a few seconds and try again.",
          details: message
        },
        { status: 503 }
      );
    }

    return NextResponse.json(
      {
        error: "Failed to update plan options.",
        details: message
      },
      { status: 500 }
    );
  }
}
