"""add agent_requests table

Revision ID: bc2da90f0a71
Revises: 
Create Date: 2026-04-25 02:41:40.527284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2da90f0a71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('trip_day_unique'), table_name='itinerary_days')
    op.create_unique_constraint('trip_day_unique', 'itinerary_days', ['trip_id', 'day_number'])
    op.drop_index(op.f('users_email_unique'), table_name='users')
    op.create_unique_constraint('users_email_unique', 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('users_email_unique', 'users', type_='unique')
    op.create_index(op.f('users_email_unique'), 'users', ['email'], unique=True)
    op.drop_constraint('trip_day_unique', 'itinerary_days', type_='unique')
    op.create_index(op.f('trip_day_unique'), 'itinerary_days', ['trip_id', 'day_number'], unique=True)
    op.drop_table('agent_requests')
    # ### end Alembic commands ###
